apiVersion: v1
kind: Service
metadata:
  name: go-api-primary-service
  namespace: go-api-namespace
spec:
  selector:
    app: go-api
    version: blue  # Initially points to "blue"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP  # Or LoadBalancer if external
